### ISSUE TITLE
What's the password

### ISSUE THREAD

**Issue by chcGolang** [nkpro2000sr/Chrome-VNC#1]

**Comment by nkpro2000sr** [comment]
**user name :** user
**password   :** passwd
> https://github.com/nkpro2000sr/Chrome-VNC/blob/092fc0e8506fd53c2ff6fc4414595c7c861b0f21/Dockerfile#L12

*user added in sudoers file*
> https://github.com/nkpro2000sr/Chrome-VNC/blob/092fc0e8506fd53c2ff6fc4414595c7c861b0f21/Dockerfile#L13

**VNC password :** passwd
> https://github.com/nkpro2000sr/Chrome-VNC/blob/092fc0e8506fd53c2ff6fc4414595c7c861b0f21/Dockerfile#L16
