### ISSUE TITLE
password

### ISSUE THREAD

**Issue by leungzw** [nkpro2000sr/Chrome-VNC#2]
I build a container with
docker run --rm -it -p 5900:5900 -e RESOLUTION=1280x720x24 nkpro/chrome-vnc,
when I open IP:5900/vnc.html, a password was NEEDed, 
what is the password?
Thanks with regards.

**Comment by nkpro2000sr** [comment]
https://github.com/nkpro2000sr/Chrome-VNC/commit/0cdaf1c9ba16795cec543aab3ff95037a58947a8
